import { RoboticPart, Chassis, QuizQuestion } from "./types";

export const CHASSIS_LIST: Chassis[] = [
  {
    id: "rover_wheeled",
    name: "4-Wheeled Mars Rover Chassis",
    description: "Highly maneuverable mobility platform. Perfect for obstacle avoidance, line tracking, and outdoor exploratory bots.",
    maxSlots: 4,
    icon: "Truck",
  },
  {
    id: "arm_robotic",
    name: "Articulated Robotic Arm base",
    description: "Stationary multi-axis manipulator with angular hinges. Perfect for pick-and-place trials, sorting, and geometric solvers.",
    maxSlots: 3,
    icon: "Wrench",
  },
  {
    id: "crawler_tank",
    name: "Treaded Crawler Tank Chassis",
    description: "Heavy-duty dual tracked layout. Excellent for traversing rough terrain, climbing debris, and high-torque pulling.",
    maxSlots: 4,
    icon: "Component",
  },
];

export const ROBOTIC_PARTS: RoboticPart[] = [
  // controllers
  {
    id: "controller_arduino",
    name: "Arduino Uno R3",
    category: "microcontroller",
    symbol: "C-ARD",
    shortDesc: "Standard 8-bit MCU starter board.",
    description: "The classic general-purpose microcontroller board powered by the ATmega328P. Operates at a clock speed of 16MHz. Highly suited for real-time digital input/output, processing simple control cycles, and triggering servomotors smoothly.",
    howItWorks: "Under the hood, it executes a binary instruction sequence compiled from Arduino C++. It features an 8-bit CPU that processes instructions one and only one at a time, checking inputs (sensors) and setting outputs (actuators) continuously in an infinite microsecond loop.",
    realWorldExample: "Used inside 3D printers for direct thermal/gantry control, home automated systems, smart clocks, and wheeled research rovers.",
    connections: "Has pins D0 through D13 for digital input/output, and analog input pins A0 through A5.",
    parameters: [
      { label: "Processor", value: "ATmega328P (8-bit)" },
      { label: "Clock Speed", value: "16 MHz" },
      { label: "Operating Voltage", value: "5V (I/O compatible)" },
      { label: "Flash Memory", value: "32 KB (For firmware)" },
    ],
    trivia: "The Arduino project was started in Ivrea, Italy, in 2005 to provide a low-cost, easy-to-use microcontroller teaching kit for design students.",
    hotspots: [
      { id: "ard_mcu", name: "ATmega328P microchip", description: "The core 'brain' IC that contains the ALU, registers, and memory. It compiles your instructions into flash storage and executes them.", x: 50, y: 65 },
      { id: "ard_usb", name: "USB-B Port", description: "Standard secure hardware interface used to upload new code from your PC and provides USB serial debugging outputs.", x: 12, y: 22 },
      { id: "ard_power", name: "Barrel Power Jack", description: "Allows external batteries (7-12V) to safely power the system through any direct DC power supply adapter.", x: 13, y: 72 },
      { id: "ard_reg", name: "Voltage Regulator IC", description: "Converts varying battery source voltages (e.g., 9V) down to a stable, noise-free 5V or 3.3V to protect electronic gates.", x: 26, y: 65 },
      { id: "ard_pins_d", name: "Digital GPIO Rail", description: "Inputs or outputs operating at high (5V) or low (0V). Six of these offer PWM (Pulse Width Modulation) to control precise analog actuators.", x: 62, y: 8 },
      { id: "ard_pins_a", name: "Analog Inputs (A0-A5)", description: "Contains an internal ADC (Analog-to-Digital Converter) which quantifies smooth sensor voltages (0-5V) to 10-bit integer coordinates (0-1023).", x: 74, y: 88 },
    ],
  },
  {
    id: "controller_esp32",
    name: "ESP32 Dev Module",
    category: "microcontroller",
    symbol: "C-ESP",
    shortDesc: "High-speed Dual-Core 32-bit CPU with built-in Wi-Fi.",
    description: "A highly robust, ultra-fast 32-bit microcontroller featuring powerful dual Tensilica cores, high speed hardware timers, and built-in Wi-Fi and Bluetooth communication modules.",
    howItWorks: "Runs at speeds up to 240MHz, offering multiple megabytes of storage. Ideal for advanced robots requiring internet connection, over-the-air web-server controls, remote video streaming, or multi-threaded loop scheduling.",
    realWorldExample: "Integrates inside IoT weather monitors, home security drones, smart wearables, and industrial smart warehouse dollies.",
    connections: "Powered with 3.3V, features robust digital GPIO busses, SPI, I2C lanes, and dual Analog DAC converters.",
    parameters: [
      { label: "Processor", value: "Xtensa 32-bit Dual-Core" },
      { label: "Clock Speed", value: "240 MHz (Super speedy!)" },
      { label: "Operating Voltage", value: "3.3V logic levels" },
      { label: "Wireless", value: "Wi-Fi 802.11 b/g/n & BLE" },
    ],
    trivia: "The ESP32 was released by Espressif Systems in Shanghai, causing a revolution in cheap IoT manufacturing due to its combined wireless connectivity and raw CPU performance.",
    hotspots: [
      { id: "esp_cpu", name: "Tensilica dual-core chip", description: "Highly capable CPU that handles wireless network stacks in the background while running user motion control scripts on the secondary core.", x: 50, y: 38 },
      { id: "esp_ant", name: "Onboard PCB Antenna", description: "Sinuous trace printed directly on the terminal board. Optimizes sending and receiving 2.4GHz radio signals for Wi-Fi and bluetooth.", x: 50, y: 8 },
      { id: "esp_usb", name: "Micro-USB port", description: "Provides communication to flash system firmware and supplies USB power for desktop testing.", x: 50, y: 92 },
      { id: "esp_boot", name: "Boot & En Buttons", description: "Used on some developer cards to force the bootloader into upload mode or execute a hardware system restart.", x: 18, y: 82 },
    ],
  },
  {
    id: "controller_driver_l298n",
    name: "L298N Dual Motor Driver",
    category: "motordriver",
    symbol: "C-DRV",
    shortDesc: "High-current H-Bridge for DC motor power.",
    description: "The L298N module acts as the heavy-duty muscle intermediary. Since low-power microcontrollers can only output tiny amounts of current, this driver takes digital high/low motor signals and redirects substantial battery voltage straight to high-power inductive motors.",
    howItWorks: "Uses H-bridge structures to cross-connect transistors. Closing diagonally opposite transistor pairs allows current to drive forward; closing the alternate pair swaps the polarity, forcing the motor to spin backward.",
    realWorldExample: "Found in automated vacuum cleaners, educational crawler tanks, and sorting belts.",
    connections: "Connect digital PWM inputs to configure speed (ENA, ENB), and standard digital lines to configure rotation direction (IN1, IN2, IN3, IN4).",
    parameters: [
      { label: "Dual H-Bridge IC", value: "L298 Pin-array chip" },
      { label: "Output Voltage Limits", value: "5V to 35V DC supply" },
      { label: "Peak Current Output", value: "Up to 2A per continuous motor channel" },
      { label: "Internal Heat dissipator", value: "Heavy aluminum heat-sink fins" },
    ],
    trivia: "The L298 is an older transistor-based IC that has a noticeable voltage drop (~1.4V to 2V) due to internal bipolar transistors. Modern boards often replace it with MOSFET-based drivers like TB6612FNG for higher electrical efficiency.",
    hotspots: [
      { id: "drv_ic", name: "L298 Multiwatt IC", description: "The central silicon package containing dual H-bridges. Handles high currents and switches currents up to 2 Amps per motor channel.", x: 50, y: 38 },
      { id: "drv_sink", name: "Aluminum Heatsink", description: "Heavy metal design that draws mechanical heat away from the silicon junctions to protect them during high-load high-traction scenarios.", x: 50, y: 15 },
      { id: "drv_term_m", name: "Motor Output Screw Terminals", description: "Heavy-duty clamp ports designed to wire screw conductors directly to left and right DC drive motors.", x: 8, y: 62 },
      { id: "drv_term_p", name: "External Battery Input terminals", description: "Safe direct connection point for high-voltage batteries (12V) and central system chassis ground bonds.", x: 42, y: 88 },
      { id: "drv_jump", name: "5V Regulator Enable jumper", description: "Small physical shunt. When inserted, it routes battery down to internal logic pins, removing the need for alternative dual controller lines.", x: 26, y: 75 },
    ],
  },

  // actuators
  {
    id: "actuator_servo_sg90",
    name: "SG90 Precision Servo Motor",
    category: "actuator",
    symbol: "A-SRV",
    shortDesc: "Precise angular rotation actuator (0-180°).",
    description: "An incredibly popular micro-servo motor designed for precise angular adjustments. It doesn't spin endlessly; instead, it is driven to a specific target angle (like 45° or 120°) and fights to maintain that exact physical position under load.",
    howItWorks: "Uses an internal closed-loop feedback design. The controller sends a PWM pulse (1.0ms - 2.0ms duty cycles) representing the desired angle. An internal IC compares the voltage from a built-in feedback potentiometer with the command pulse, spinning a coreless motor in the direction that minimizes structural angular error.",
    realWorldExample: "Used to toggle mechanical claws, control steering axles in remote controlled cars, and activate humanoid mechanical joints.",
    connections: "Wired with 3 primary lines: Brown (Ground), Red (Power Core, 5V), and Orange (PWM control signal wire).",
    parameters: [
      { label: "Rotation Limit", value: "180 Degrees total radius" },
      { label: "Internal Gearing", value: "Nylon reduction composite teeth" },
      { label: "Mechanical Torque", value: "1.8 kg-cm @ 4.8V" },
      { label: "Control Clock Frame", value: "50Hz Standard Servo Frequency" },
    ],
    trivia: "An angle representation pulse width of 1.5 milliseconds is the standard universal neutral (90°) orientation command for a wide variety of model aircraft servos.",
    hotspots: [
      { id: "srv_horn", name: "Mechanical Output Horn", description: "The plastic arm connected to the terminal gear. You screw functional pushrods, levers, or linkages onto these holes.", x: 50, y: 15 },
      { id: "srv_gears", name: "Reduction Gearbox", description: "A system of high-reduction plastic gears that convert high speed spinning motor cycles into robust high-force output rotations.", x: 50, y: 38 },
      { id: "srv_motor", name: "Miniature Coreless DC Motor", description: "A lightweight motor that spins when high-speed current runs through it, initiating the movement of the gear layers.", x: 32, y: 64 },
      { id: "srv_pot", name: "Internal Potentiometer", description: "Wired directly to the steering shaft. Acts as a variable resistor that provides an analog voltage feedback proportional to the exact angle.", x: 68, y: 64 },
      { id: "srv_ic", name: "Miniature Controller IC Board", description: "The brains inside the servo. Compares the pulses coming in on the yellow signal wire with the state of the potentiometer, correcting DC motor power cycles on the fly.", x: 50, y: 86 },
    ],
  },
  {
    id: "actuator_dc_geared",
    name: "Geared Hobby DC Motor",
    category: "actuator",
    symbol: "A-DCM",
    shortDesc: "High-speed continuous rotation hobby motor.",
    description: "Standard continuous rotation motor fitted with a high ratio reduction gearbox. Provides continuous forward or backward rotation which makes it excellent for driving robot wheels.",
    howItWorks: "Relies on magnetic forces inside. When electrical current passes through the rotor coils, it creates an electromagnet that repels and attracts the stator's permanent magnets. Switching polarities causes constant rotation. The yellow plastic gearbox lowers speed from early thousands of RPMs to usable wheel turns (~150 RPM) and multiples mechanical pull force.",
    realWorldExample: "Wired onto small line-following buggies, robotic warehouse loaders, and simple automated sweepers.",
    connections: "Requires only two lead wires. Swap the wire polarities to invert the rotation rotation direction.",
    parameters: [
      { label: "Gear reduction ratio", value: "1:48 standard" },
      { label: "No-load output speed", value: "125 RPM @ 3V, 200 RPM @ 6V" },
      { label: "Traction Shafts", value: "Dual flat sides (suited for wheels with snap locks)" },
      { label: "Average running current", value: "~150mA under direct chassis load" },
    ],
    trivia: "DC motors generate EMF (Electromotive Force) noise. Soldering small 0.1uF ceramic capacitors across motor terminals helps filter out electromagnetic noise from scrambling adjacent microcontrollers.",
    hotspots: [
      { id: "dc_term", name: "Solder lead Terminals", description: "External connection tabs designed for stranded wiring. Reversing relative positive and negative leads swaps direction.", x: 12, y: 50 },
      { id: "dc_brush", name: "Brushes & Commutator", description: "Physical contacts that constantly deliver current to the spinning copper coils, manually switching polarity to keep the motor spinning.", x: 28, y: 50 },
      { id: "dc_rotor", name: "Coils and rotor", description: "Insulated copper turns that form strong magnetic electro-fields when dynamic power flows through.", x: 42, y: 50 },
      { id: "dc_gears", name: "Spur Gear Train", description: "Successive modular polymer gears that step down motor shaft speeds, multiplying immediate wheel torque.", x: 74, y: 50 },
    ],
  },
  {
    id: "actuator_stepper",
    name: "NEMA 17 Stepper Motor",
    category: "actuator",
    symbol: "A-STP",
    shortDesc: "High-torque incremental rotation stepper.",
    description: "A heavy-duty high-resolution continuous motor that divides a full 360-degree rotation into 200 exact micro steps (1.8° per step). Highly prized for holding stability and extreme point-to-point path precision.",
    howItWorks: "The stator features multiple coils grouped into 'phases'. Energizing these phases sequentially magnetically snaps the geared iron rotor to the active electromagnet pole. By repeating this pulse process, the machine steps in precise, repeatable physical increments.",
    realWorldExample: "The foundational motor inside desktop 3D Printers, CNC routers, industrial laser cutters, and precise robotic arms.",
    connections: "Usually wired as a 4-wire bipolar motor config (Phase A+, A-, B+, B-), driven with controllers like the A4988 chip.",
    parameters: [
      { label: "Steps per Revolution", value: "200 (1.8 Degrees Angle change)" },
      { label: "Holding torque", value: "40 Ncm (Ultra-stiff grip)" },
      { label: "Phase resistance", value: "1.5 Ohms" },
      { label: "Form factor standard", value: "NEMA 17 face dimensions" },
    ],
    trivia: "Unlike DC motors which consume minimal idle power, steppers consume full rated current draw when completely stopped to maintain their rigid 'locked' holding angle.",
    hotspots: [
      { id: "stp_shaft", name: "D-Shape output shaft", description: "Flat-faced steel shaft. Helps keep drive pullies or couplers from slipping under massive load cycles.", x: 50, y: 20 },
      { id: "stp_rot", name: "Teethed Iron Rotor", description: "The central magnet stack with dozens of fine steel ridges that align precisely with stator electromagnet pulses.", x: 50, y: 56 },
      { id: "stp_coils", name: "Stator Phase Windings", description: "Heavy copper coil blocks positioned around the chassis perimeter. Powered selectively in patterns by driver units.", x: 26, y: 56 },
      { id: "stp_socket", name: "4-pin Molex Connector", description: "Central wiring jack routing control waveforms to the two internal isolated coils.", x: 50, y: 88 },
    ],
  },

  // sensors
  {
    id: "sensor_ultrasonic",
    name: "HC-SR04 Ultrasonic Sensor",
    category: "sensor",
    symbol: "S-ULS",
    shortDesc: "Sonic distance finder (2cm - 400cm limit).",
    description: "A super popular, low-cost sensor that calculates proximity. Features two metallic mesh mesh canisters resembling robot binoculars—one acts as a speaker, the other a microphone.",
    howItWorks: "The controller sends a 10-microsecond trigger pulse. The sensor then fires an ultra-high frequency acoustic wave (40kHz) out of its transmitter. It measures the microseconds it takes for the echo to bounce off an obstacle and return to the receiver. The microcontroller calculates distance: Distance = (Time * Speed of Sound) / 2.",
    realWorldExample: "Enables distance warnings, drone terrain sensors, automatic flush toilets, and wall-hugging robots.",
    connections: "Connect to pins: VCC (5V power line), Trig (Input to shoot acoustic cone), Echo (Output returning pulse duration), and GND.",
    parameters: [
      { label: "Max detection range", value: "400 cm (approx. 13 feet)" },
      { label: "Ranging precision", value: "3 mm tolerance" },
      { label: "Sonar cone angle", value: "15 Degrees coverage" },
      { label: "Working current", value: "15mA nominal" },
    ],
    trivia: "Because bats navigate using high-frequency echo timing, the HC-SR04 essentially performs the same biological echolocation trick to gauge robot coordinates!",
    hotspots: [
      { id: "ult_trig_pod", name: "Ultrasonic Transmitter T-Pod", description: "A high-frequency piezoelectric transducer. It vibrates rapidly at 40,000Hz when triggered, projecting soundwaves into the air.", x: 26, y: 50 },
      { id: "ult_echo_pod", name: "Ultrasonic Receiver R-Pod", description: "A highly sensitive sound cone that waits for the 40kHz sonic bounce. It vibrates when the sound hits it, sending a small current to the amplifier.", x: 74, y: 50 },
      { id: "ult_ic", name: "Signal Processing IC", description: "The microchip that handles trigger signals, drives the transmitter, amplifies the micro-volt receiver vibrations, and outputs a visual pulse duration on the Echo pin.", x: 50, y: 86 },
      { id: "ult_pins", name: "4-Pin Header Interface", description: "The physical connections: VCC (5V), Trig (Input pulse), Echo (Output duration pulse), GND (Common reference ground path).", x: 50, y: 15 },
    ],
  },
  {
    id: "sensor_imu_mpu6050",
    name: "MPU-6050 Accelerometer + Gyro",
    category: "sensor",
    symbol: "S-IMU",
    shortDesc: "Orientation and balance IMU tracker.",
    description: "An Inertial Measurement Unit (IMU) featuring a triple-axis accelerometer and triple-axis gyroscope inside a single tiny silicon wafer. Vital for tilt-detection, balancing, and orientation analytics.",
    howItWorks: "The gyroscope senses angular rates (rotation degrees/sec) using micro-machined silica structures. The accelerometer measures gravity vectors and physical impacts. Combining these via software (like a Kalman filter) produces rock-solid orientation angles (pitch, roll, yaw) despite vibration.",
    realWorldExample: "Keeps quadcopter drones level, manages self-balancing Segway unicycles, and tracks virtual reality controller positions.",
    connections: "Communicates using the I2C bus protocol, requiring VCC (3.3V or 5V-regulated), GND, SDA (Data), and SCL (Clock).",
    parameters: [
      { label: "Measurement axes", value: "6 Axes total (3 Accel, 3 Gyro)" },
      { label: "Gyro scope scale", value: "Up to ±2000 degrees per sec" },
      { label: "Accelerometer index", value: "Up to ±16g capacity" },
      { label: "Interface Bus type", value: "I2C standard interface" },
    ],
    trivia: "The tiny mechanical sensors inside are made using MEMS (Micro-Electro-Mechanical Systems) technology, where microscopic mechanical combs and springs are etched directly into silicon at micrometer scale!",
    hotspots: [
      { id: "imu_sensor_chip", name: "MPU-6050 MEMS IC", description: "The miniature silicon chip that contains microscopic vibrating combs and plates. Senses tiny mechanical deviations and converts them to digital register data.", x: 50, y: 50 },
      { id: "imu_caps", name: "Smoothing Capacitors", description: "Tiny ceramics that filter out power noise, ensuring the digital sensor readings remain clean and jitter-free.", x: 18, y: 24 },
      { id: "imu_pullup", name: "I2C Bus Pullup Resistors", description: "Keeps SDA and SCL lines floating high so that multiple digital devices don't step on each other's digital toes.", x: 78, y: 24 },
      { id: "imu_header", name: "I2C Terminal Pins", description: "The pinout connections: VCC, GND, SCL (Serial Clock), SDA (Serial Data), INT (hardware interrupt pin to alert MCU when new movement occurs).", x: 50, y: 88 },
    ],
  },
  {
    id: "sensor_camera",
    name: "AI Smart Vision Camera Module",
    category: "sensor",
    symbol: "S-CAM",
    shortDesc: "Sensing lens for color, tag, and shape tracking.",
    description: "An interactive computer vision camera fitted with local processing capacity. Instantly tracks, extracts, and transmits coordinates for colors, shapes, QR codes, and apriltags back to a master microcontroller.",
    howItWorks: "A CMOS optical lens captures light patterns, mapping raw pixels directly onto local RAM frames. An internal processor evaluates colors under edge-detection systems, grouping similar pixel segments and outputting simplified targets (like 'Object Bounding Box [X:120, Y:75, W:50, H:60]') over serial interfaces.",
    realWorldExample: "Powers sorting robots sorting luggage, warehouse barcode pickers, and autonomous obstacle-skirting bots.",
    connections: "Connects via RX/TX UART lines or I2C data lanes at 3.3V power.",
    parameters: [
      { label: "Frame resolutions", value: "VGA 640 x 480 pixels" },
      { label: "Frame scan-rate", value: "Up to 60 Frames per sec" },
      { label: "Visual functions", value: "Face detect, color codes, tags" },
      { label: "Interface Standard", value: "Serial RX/TX (115200 baudrate)" },
    ],
    trivia: "Advanced smart cameras use tiny neural networks (CNNs) accelerated directly by localized hardware hardware matrices inside the camera's silicon chip!",
    hotspots: [
      { id: "cam_lens", name: "Adjustable Focus Lens", description: "Gathers light and aligns it perfectly onto the sensor surface. Adjusting the lens allows sharp close-range or far-range focus.", x: 50, y: 32 },
      { id: "cam_sensor", name: "CMOS Matrix Array", description: "An array of millions of light-sensing pixels. Translates light photons into analog electricity levels, matching them to Red, Green, and Blue sub-pixels.", x: 50, y: 52 },
      { id: "cam_dsp", name: "Image Co-processor", description: "A high-speed DSP chip that executes real-time digital filtering, thresholding, and color segmentation algorithms.", x: 74, y: 74 },
      { id: "cam_pins", name: "Pins", description: "Routes digital command strings, serial UART protocols, and regulates electrical voltages.", x: 26, y: 88 },
    ],
  },
  {
    id: "controller_raspberry_pi",
    name: "Raspberry Pi 4 Model B",
    category: "microcontroller",
    symbol: "C-RPI",
    shortDesc: "High-performance Quad-Core 64-bit Small Board Computer.",
    description: "A full-fledged, high-performance Single-Board Computer (SBC) running on a Broadcom quad-core processor. Suitable for advanced robotic applications running Linux, ROS (Robot Operating System), compute-heavy computer vision pipelines, and localized AI inferences.",
    howItWorks: "Unlike simple microcontrollers, this is a true computer running an entire Linux OS. It interacts with raw hardware through its 40-pin GPIO header while concurrently rendering desktop screens, reading cameras or LiDAR lines, and maintaining wireless background threads.",
    realWorldExample: "Powers complex automated delivery bots, autonomous warehouse machinery, and high-precision mapping rovers.",
    connections: "Features a standard 40-pin GPIO expansion header (supporting SPI, I2C, UART), 4 USB ports, and dual micro-HDMI output ports.",
    parameters: [
      { label: "Processor", value: "Broadcom BCM2711 Quad-Core" },
      { label: "Clock Speed", value: "1.5 GHz 64-bit" },
      { label: "RAM Memory", value: "4 GB LPDDR4 Core" },
      { label: "Operating System", value: "Raspberry Pi OS (Linux kernel)" },
    ],
    trivia: "The Raspberry Pi project was originally created in the UK as an educational board, but exploded in popularity globally as the foundation for modern DIY and smart industrial hubs.",
    hotspots: [
      { id: "rpi_cpu", name: "Broadcom SoC CPU", description: "The powerful main processor running 4 quad-core ARM Cortex-A72 lanes capable of running localized software threads.", x: 42, y: 44 },
      { id: "rpi_ram", name: "LPDDR4 Memory Chip", description: "Dual-channel LPDDR4 memory cache that provides high bandwidth for live tasks and operational code executions.", x: 42, y: 64 },
      { id: "rpi_gpio", name: "40-Pin GPIO Header", description: "Standard physical interfacing rail supporting digital sensors, relays, and hardware connection pins.", x: 92, y: 50 },
      { id: "rpi_usb", name: "USB 3.0 / 2.0 Ports", description: "Dual USB interfaces suited for smart visual camera modules, telemetry connectors, or disk mounts.", x: 74, y: 88 },
    ],
  },
  {
    id: "controller_jetson_nano",
    name: "NVIDIA Jetson Nano",
    category: "microcontroller",
    symbol: "C-JET",
    shortDesc: "Edge AI platform with 128-core Maxwell GPU.",
    description: "A powerful, compact computer designed for Edge AI applications. It packs a 128-core NVIDIA Maxwell GPU alongside a quad-core ARM processor, allowing it to run multiple neural networks in parallel for applications like image classification, object detection, segmentation, and speech processing.",
    howItWorks: "Runs a full Ubuntu Linux distribution and leverages CUDA deep learning libraries. The quad-core ARM CPU handles standard operating system tasks, while the 128-core GPU parallelizes matrix calculations vital for computer vision and neural net inference directly on the robotic chassis.",
    realWorldExample: "Powers autonomous mobile robots (AMRs), advanced self-driving delivery bots, facial recognition access portals, and smart sorting conveyor systems with real-time semantic segmentation.",
    connections: "Equipped with a 40-pin GPIO header, 4 USB 3.0 ports, HDMI/DisplayPort outputs, and a MIPI CSI-2 camera connector port.",
    parameters: [
      { label: "Processor", value: "Quad-Core ARM A57 @ 1.43 GHz" },
      { label: "GPU Cores", value: "128-core NVIDIA Maxwell™" },
      { label: "Memory RAM", value: "4 GB 64-bit LPDDR4 @ 25.6 GB/s" },
      { label: "AI Performance", value: "472 GFLOPS (FP16)" },
    ],
    trivia: "The Jetson Nano is incredibly power-efficient, supporting selectable power modes of 5 watts or 10 watts to preserve battery life on small robotic vehicles.",
    hotspots: [
      { id: "jet_gpu", name: "Tegra Maxwell GPU/CPU SoC", description: "The central processing engine of the Jetson, covered by a large heatsink, that enables deep learning inference with CUDA acceleration.", x: 45, y: 48 },
      { id: "jet_ram", name: "LPDDR4 Memory Modules", description: "High-speed shared unified memory architecture which provides low-latency access for both CPU and GPU operations.", x: 25, y: 35 },
      { id: "jet_gpio", name: "40-Pin Expansion Header", description: "Fully compatible with many Raspberry Pi add-on boards, offering I2C, SPI, UART, and PWM signals.", x: 92, y: 32 },
      { id: "jet_usb", name: "Quad USB 3.0 Ports", description: "High-speed ports for connecting multiple optical cameras, Intel RealSense depth sensors, or high-bandwidth USB peripherals.", x: 74, y: 76 },
    ],
  },
  {
    id: "controller_driver_pca9685",
    name: "PCA9685 16-Ch Servo Driver",
    category: "motordriver",
    symbol: "C-PCA",
    shortDesc: "16-Channel 12-bit PWM generator driven by I2C.",
    description: "A dedicated 12-bit PWM helper board controlled via the simple I2C bus. Ideal for robotic chassis like hexapods or robotic arms that require controlling up to 16 independent servo motor channels using only 2 microcontroller pins.",
    howItWorks: "Understands custom registers written over SDA/SCL. An internal high-stability 25MHz clock generates precise, jitter-free PWM signals independently from the main CPU, ensuring servos remain perfectly stable under heavy load conditions without wasting processor instruction cycles.",
    realWorldExample: "Found in autonomous walking spider hexapods, advanced robotic hands, and multiaxial stationary mechanical shoulders.",
    connections: "Requires 4 communication lines (VCC, GND, SDA, SCL) and a high-current external battery connection for servo power rails.",
    parameters: [
      { label: "Output Channels", value: "16 Independent PWM lines" },
      { label: "PWM Resolution", value: "12-bit (4096 individual steps)" },
      { label: "Interface Protocol", value: "I2C Bus (Addresses: 0x40-0x7F)" },
      { label: "External Power", value: "5V-6V terminal block for servos" },
    ],
    trivia: "The PCA9685 supports daisy-chaining, which means by linking multiple drivers together, a single microcontroller can control up to 992 servo motors!",
    hotspots: [
      { id: "pca_chip", name: "PCA9685 Controller Chip", description: "The core I2C-to-PWM generator. Runs its own internal 25MHz clock to output precise, flicker-free signals.", x: 50, y: 50 },
      { id: "pca_term", name: "Power Terminal Block", description: "Screw terminal clamps designed for heavy-current 5-6V hobby batteries to power the connected servos directly.", x: 42, y: 15 },
      { id: "pca_servo_headers", name: "Servo Connection Headers", description: "16 groups of 3-pin headers (Signal, Power, Ground) mapped beautifully for direct plug-and-play servo cables.", x: 50, y: 85 },
      { id: "pca_cap", name: "Power filter capacitor", description: "A high-capacity electrolytic capacitor that buffers high-current noise surges when multiple high-torque servos adjust angles at once.", x: 18, y: 22 },
    ],
  },
  {
    id: "actuator_buzzer",
    name: "Active Piezo Buzzer Module",
    category: "actuator",
    symbol: "A-BUZ",
    shortDesc: "Audible alarm and trigger alert buzzer.",
    description: "A classic direct-drive active audio buzzer. Perfect for emitting diagnostic sound alarms, user prompts, boundary notifications, or system alerts when state abnormalities occur.",
    howItWorks: "Contains an internal high-frequency oscillator. It does not need an external AC soundwave signal; simply toggling the control pin High (5V) triggers the internal oscillator, causing a piezoelectric ceramic disk to flex rapidly and project a high-pitch 2.5kHz warning tone.",
    realWorldExample: "Used in factory temperature alarms, microwave status sounds, automated security systems, and collision alerting rovers.",
    connections: "Requires 3 pins: VCC (5V), I/O Signal Pin (Active HIGH), and Ground (GND).",
    parameters: [
      { label: "Acoustic Pitch", value: "2.5 kHz ± 300Hz" },
      { label: "Sound Output", value: "85 dB at 10cm distance" },
      { label: "Working Current", value: "< 30mA average" },
      { label: "Driver System", value: "Built-in oscillator (Active type)" },
    ],
    trivia: "The word piezoelectric comes from the Greek 'piezein', which means to squeeze or press. Mechanical stress on materials like quartz crystals directly generates electricity, and vice versa!",
    hotspots: [
      { id: "buz_can", name: "Canister Housing", description: "A resonant plastic chamber that focuses and amplifies the acoustic sound wave vibrations forward.", x: 50, y: 44 },
      { id: "buz_piezo", name: "Vibrating Ceramic Disk", description: "A wafer-thin piezoelectric element glued to a brass disk. Expands and contracts when voltage is applied, generating sound waves.", x: 50, y: 64 },
      { id: "buz_transistor", name: "SOT-23 Driver Transistor", description: "A tiny surface-mount transistor that switches the higher buzzer current safely using simple low-current microcontroller logic.", x: 26, y: 78 },
      { id: "buz_header", name: "3-Pin Control Interface", description: "Standard layout: VCC, Signal (Trigger input), and GND (Common ground rail).", x: 74, y: 88 },
    ],
  },
  {
    id: "sensor_ir_tracker",
    name: "IR Line Tracking Sensor",
    category: "sensor",
    symbol: "S-IRT",
    shortDesc: "Infrared surface reflectivity detector.",
    description: "An infrared reflectivity sensor module used primarily for path recognition and line tracking. Essential for guiding wheeled rovers along high-contrast dark lines taped on light floors.",
    howItWorks: "Projects infrared light from an emitter LED. An adjacent phototransistor measures how much light bounces back. Safe light surfaces reflect strong IR rays, while dark lines absorb the light, letting the microcontroller detect transitions instantly.",
    realWorldExample: "Wired onto robotic AGVs (Automated Guided Vehicles) inside heavy manufacturing hubs to follow dedicated ground lines safely.",
    connections: "Connects using 3 simple pins: VCC (5V or 3.3V), OUT (Digital high/low reflection signal), and GND.",
    parameters: [
      { label: "Detection Distance", value: "1cm - 2.5cm optimal" },
      { label: "Adjustable Threshold", value: "Multi-turn trim potentiometer" },
      { label: "Signal Latency", value: "< 1 millisecond response" },
      { label: "Operating Voltage", value: "3.3V to 5V dual compatible" },
    ],
    trivia: "Many digital cameras capture infrared light. If you look at an active IR tracking emitter through a smartphone camera, you can see a faint violet glow that is invisible to human eyes!",
    hotspots: [
      { id: "ir_emitter", name: "IR Emitter LED (Clear)", description: "Constantly emits focused infrared light patterns pointing downwards at the ground surface.", x: 18, y: 50 },
      { id: "ir_receiver", name: "IR Phototransistor (Black)", description: "A light-sensitive silicon sensor tuned specifically to detect reflected infrared light angles.", x: 82, y: 50 },
      { id: "ir_comparator", name: "LM393 analog comparator chip", description: "A small integrated circuit that translates smooth analog light levels into clean, digital high/low logic signals.", x: 50, y: 74 },
      { id: "ir_trimmer", name: "Sensitivity Potentiometer", description: "A tiny screw trimmer that adjusts the baseline threshold voltage, changing how reflective a surface must be to trigger a return pulse change.", x: 50, y: 24 },
    ],
  },
  {
    id: "sensor_ir_obstacle",
    name: "IR Obstacle Avoidance Sensor",
    category: "sensor",
    symbol: "S-IRO",
    shortDesc: "Short-range infrared proximity switch.",
    description: "An active infrared proximity sensor designed to detect obstacles in front of your robot. Extremely popular for basic collision avoidance on small mobile rovers.",
    howItWorks: "Consists of an IR emitter shooting infrared light forward. When a physical obstacle enters the path, the light bounces back, is captured by an IR receiver photodiode, and triggers an LM393 comparator to output a digital LOW signal.",
    realWorldExample: "Proximity detection on automated vacuum cleaners, factory bottle counting lines, and automatic paper towel dispensers.",
    connections: "VCC (3.3V-5V), GND, OUT (Digital logic output).",
    parameters: [
      { label: "Optimal Range", value: "2cm to 30cm distance" },
      { label: "Sensor Type", value: "Active Photoelectric" },
      { label: "Adjustable Threshold", value: "Single-Turn Trimmer" },
    ],
    trivia: "These sensors perform wonderfully on light-colored walls, but can fail to detect dark black objects because black surfaces absorb almost all infrared light wavelengths!",
    hotspots: [
      { id: "iro_emitter", name: "Infrared Emitter LED", description: "Fires a constant stream of 950nm infrared light beams straight forward.", x: 20, y: 30 },
      { id: "iro_receiver", name: "Infrared Photo Receiver", description: "Registers reflected backbound light when an obstacle crosses the path.", x: 20, y: 70 },
      { id: "iro_trimmer", name: "Distance Calibration Screw", description: "A high-tolerance single-turn potentiometer adjusting baseline trigger distance.", x: 50, y: 50 },
      { id: "iro_comparator", name: "LM393 Operational IC", description: "Compares clean received voltages with the trimmer to flip digital output switches.", x: 80, y: 50 }
    ],
  },
  {
    id: "sensor_pir_motion",
    name: "HC-SR501 PIR Motion Sensor",
    category: "sensor",
    symbol: "S-PIR",
    shortDesc: "Passive infrared heat-signature motion detector.",
    description: "A passive heat-seeking motion detector that detects movement of warm objects like humans, dogs, or heated machinery by measuring shifts in ambient thermal radiation.",
    howItWorks: "Contains dual pyroelectric crystal elements inside. When a warm body moves across the sensor's field, the split elements detect a differential heat state. An onboard controller chip registers this as physical motion and outputs a high voltage logic signal.",
    realWorldExample: "Automatic floodlight switches, indoor burglar alarms, and electronic cat doors.",
    connections: "VCC (5V-12V main power), GND, OUT (3.3V static HIGH level on trigger).",
    parameters: [
      { label: "Detection Max", value: "7 meters radius" },
      { label: "Aperture Angle", value: "110° conical view" },
      { label: "Output Latch Time", value: "3 seconds to 300 seconds" },
    ],
    trivia: "The round white dome is not just a protector; it is a Fresnel lens arrays which focuses ambient IR light onto the crystals, dividing the view into dozens of hot/cold quadrants to trace movement.",
    hotspots: [
      { id: "pir_lens", name: "Fresnel Lens Cover", description: "Concentric multi-quadrant pattern dome that shapes and shifts thermal light onto sensory crystals.", x: 50, y: 30 },
      { id: "pir_pyro", name: "Biaxial Pyroelectric Core", description: "Dual heat-sensitive crystals detecting ambient movement of humans, bodies, or machines.", x: 50, y: 65 },
      { id: "pir_delay", name: "Output Latch Timer Trimmer", description: "Small rotary trim pot that calibrates how long (3s-300s) the output pin is lathed HIGH.", x: 20, y: 85 },
      { id: "pir_sensitivity", name: "Sensitivity Limit Trimmer", description: "Trimmer defining the physical range limits (3 meters to 7 meters) to trip.", x: 80, y: 85 }
    ],
  },
  {
    id: "sensor_dht11",
    name: "DHT11 Weather Sensor",
    category: "sensor",
    symbol: "S-DHT",
    shortDesc: "Climate temperature and humidity monitor.",
    description: "A popular, budget-friendly climate sensor that provides calibrated, fully digital readouts of dry-bulb temperature and ambient moisture changes.",
    howItWorks: "It measures moisture using a moisture-sensitive capacitive element, and evaluates temperature using a negative temperature coefficient (NTC) thermistor. Onboard microchip handles conversions and outputs data packets.",
    realWorldExample: "Smart garden greenhouses, smart home thermostats, and desktop weather meters.",
    connections: "VCC (3.3V-5V), DATA (Single-Bus line with external 10k pullup), GND.",
    parameters: [
      { label: "Relative Humidity", value: "20% - 90% RH (5% error)" },
      { label: "Temperature Scale", value: "0°C - 50°C (±2°C margin)" },
      { label: "Sampling Speed", value: "1 Hz (Once per second)" },
    ],
    trivia: "DHT sensors communicate over a custom single-wire bus, sending exactly 40 bits of serial humidity and temperature numbers down a single wire sequentially!",
    hotspots: [
      { id: "dht_grid", name: "Comb-shaped Capacitance Grid", description: "Exposed conductive tracks absorbing ambient humidity to warp micro-capacitance ranges.", x: 45, y: 40 },
      { id: "dht_therm", name: "NTC Termistor Element", description: "A temperature-sensitive resistor whose internal metal resistance value falls as temperature rises.", x: 45, y: 75 },
      { id: "dht_mcu", name: "8-bit Processor Bridge", description: "Calculates humidity percentages and dry-bulb temperatures, and outputs calibrated 40-bit serial packages.", x: 80, y: 60 }
    ],
  },
  {
    id: "sensor_soil_moisture",
    name: "Soil Moisture Sensor Probe",
    category: "sensor",
    symbol: "S-SLM",
    shortDesc: "Probe-style resistance dirt humidity sensor.",
    description: "An agricultural sensor that measures active water levels inside a plant's pot or outdoor garden soil, letting users track agricultural hydration.",
    howItWorks: "Measures electrical resistance between two nickel-plated probe tines. Dry dirt has very high resistance and restricts current flow, while wet soil conducts electricity easily, outputting a high analog signal.",
    realWorldExample: "Smart self-watering plant boxes, automated farm sprinklers, and soil health monitoring crawlers.",
    connections: "VCC (3.3V-5V), GND, AO (Analog feedback), DO (Digital Threshold output).",
    parameters: [
      { label: "Probe Composition", value: "Immersion Gold / Nickel Plate" },
      { label: "Dual Logics", value: "Direct Analog + Triggered Digital" },
      { label: "Current Draw", value: "Less than 35mA active" },
    ],
    trivia: "Continuous electrical current causes probe metal erosion via electrolysis! In real applications, developers only power the sensor pin right before taking a reading and power it off immediately after.",
    hotspots: [
      { id: "slm_tines", name: "Nickel-Plated Probe Tines", description: "Two metallic tines inserted directly into soil. Current flows between them via moisture pathways to measure resistance.", x: 30, y: 70 },
      { id: "slm_pot", name: "Sensitivity Trimmer Potentiometer", description: "Hardware rotary screw to set the threshold humidity level for the binary digital out (DO) pin.", x: 65, y: 45 },
      { id: "slm_logic", name: "LM393 Operational Comparator", description: "Silicon comparator chip comparing active tine voltages against the potentiometer trimmer reference.", x: 65, y: 75 },
      { id: "slm_header", name: "4-pin Header Block", description: "Delivers VCC (3.3V-5V), GND (Common Ground), AO (Analog raw output), and DO (Digital threshold trigger).", x: 85, y: 55 }
    ],
  },
  {
    id: "sensor_rain",
    name: "FC-37 Precipitation Rain Board",
    category: "sensor",
    symbol: "S-RAN",
    shortDesc: "Exposed metal grid water droplet sensor.",
    description: "An exposed micro-track rainfall board that detects the presence and volume of water drops, letting robots sense active storm boundaries.",
    howItWorks: "The sensor features an exposed trace pattern acting as an open resistor. Water drops landing on the grid bridge of copper lines complete electrical circuits, causing output voltages to rise proportional to water coverage.",
    realWorldExample: "Smart window closures, vehicle automatic windshield wipers, and weather logging stations.",
    connections: "VCC (3.3V-5V), GND, AO (Analog rain density value), DO (Digital threshold indicator).",
    parameters: [
      { label: "Substrate Type", value: "FR4 Double Sided Tin-Platings" },
      { label: "Trigger Element", value: "LM393 analog comparator" },
      { label: "Voltage Input", value: "3.3V to 5.0V dual support" },
    ],
    trivia: "To ensure drops do not pool on the tracks and mock permanent rain, automated industrial rigs mount the sensing plate at a 45-degree tilt so that leftover drops slide off automatically.",
    hotspots: [
      { id: "ran_grid", name: "Exposed Nickel-Plated Sensing Grid", description: "An open copper trace serpentine path. Liquid raindrops bridge the interlaced grid tracks to lower electrical resistance.", x: 30, y: 55 },
      { id: "ran_trimmer", name: "Threshold Potentiometer Trimmer", description: "Standard rotary resistor setting the exact precipitation level required to trigger the digital pin status.", x: 65, y: 45 },
      { id: "ran_ic", name: "LM393 High-Speed Comparator", description: "Processes the smooth grid resistance voltages into digital high/low flags based on trimmer setpoints.", x: 80, y: 70 }
    ],
  },
  {
    id: "sensor_gas_mq2",
    name: "MQ-2 Flammable Gas Sensor",
    category: "sensor",
    symbol: "S-MQ2",
    shortDesc: "Heated chemical gas detector for smoke & LPG.",
    description: "An electro-chemical gas sensor tuned to register the presence of smoke, liquefied petroleum gas (LPG), butane, methane, and clean combustible gases.",
    howItWorks: "Features an inner nickel-chrome heater coil surrounding a Tin Dioxide (SnO2) ceramic sleeve. When combustible gas molecules hit the heated SnO2 layer, the sleeve's electrical conductivity rises, boosting output voltages.",
    realWorldExample: "Domestic carbon monoxide alarms, industrial gas pipeline guards, and fire prevention drones.",
    connections: "VCC (Strictly 5.0V for heater), GND, AO (Analog density), DO (Digital flag).",
    parameters: [
      { label: "Sensed Gases", value: "Smoke, LPG, Propane, Hydrogen" },
      { label: "Density Scaling", value: "300 to 10000 ppm" },
      { label: "Heater Draw", value: "Up to 800mW (approx 150mA)" },
    ],
    trivia: "The MQ-2 requires a pre-heating warmup run of 24-48 hours on its very first launch to fully strip ambient moisture off the SnO2 layer before it can report accurate gas concentrations!",
    hotspots: [
      { id: "gas_can", name: "Stainless Steel Exploded-Proof Mesh Cover", description: "Anti-corrosive dual-layer metal mesh. Prevents external sparks from entering and igniting combustible gases, while letting gases diffuse in.", x: 35, y: 55 },
      { id: "gas_heater", name: "Nickel-Chrome 5V Heating Coil", description: "Internal heater element warming the SnO2 cylinder to high operational temperatures (400°C) to enable chemical gas adsorption.", x: 35, y: 75 },
      { id: "gas_sensor", name: "Tin Dioxide (SnO2) Ceramic Sleeve", description: "Gaseous semiconductor overlay. Adsorbing reducing gases shifts internal electronic flow resistance downward.", x: 35, y: 35 },
      { id: "gas_pot", name: "Calibration Resistor Trimmer", description: "Allows users to calibrate baseline air content voltages to eliminate indoor reference dust triggers.", x: 75, y: 45 }
    ],
  },
  {
    id: "sensor_ldr",
    name: "LDR Photocell Light Sensor",
    category: "sensor",
    symbol: "S-LDR",
    shortDesc: "Cadmium-Sulfide ambient light detector.",
    description: "An analog light-dependent resistor (LDR) Photocell that changes its electrical resistance based on the volume of current ambient light.",
    howItWorks: "Utilizes a wavy Cadmium Sulfide (CdS) compound track. Gaining photon energy frees electrons inside the CdS semiconductor, improving overall conductivity and dropping resistance from Megaohms to hundreds of Ohms.",
    realWorldExample: "Solar tracking arrays, automatic street lighting switches, and camera flash level triggers.",
    connections: "VCC, GND, AO (Smooth light values), DO (Adjustable dark trip trigger).",
    parameters: [
      { label: "Light Resistance", value: "10k to 20k Ohms at 10Lux" },
      { label: "Dark Resistance", value: "Over 1.0 Megohm in shadows" },
      { label: "Spectral Peak", value: "540nm (corresponds to human gaze)" },
    ],
    trivia: "CdS photoresistors are banned in European consumer electronics due to heavy-metal cadmium restrictions! RoHS-compliant alternatives typically use phototransistors like the TEMT6000 instead.",
    hotspots: [
      { id: "ldr_track", name: "Cadmium-Sulfide Track", description: "Wavy serpentine photo-reactive track which frees electrons and drops resistance upon light contact.", x: 50, y: 35 },
      { id: "ldr_divider", name: "Voltage Threshold Resistor", description: "A high stability 10kOhm metal resistor used to form a voltage divider network with the LDR.", x: 50, y: 70 }
    ],
  },
  {
    id: "sensor_sound",
    name: "Clap Detection Sound Sensor",
    category: "sensor",
    symbol: "S-SND",
    shortDesc: "Basic acoustic volume threshold sensor.",
    description: "A highly responsive sound volume detector designed to register immediate noise peaks, widely used in clap switches or intrusion triggers.",
    howItWorks: "Features a tiny electret condenser microphone that converts sound wave pressure into micro-volt AC signals. If these signals exceed a threshold defined by the trimmer screw, an LM393 comparator outputs a digital pulse.",
    realWorldExample: "Acoustic clap-activated switches, security panels, and smart pet toys.",
    connections: "VCC, GND, OUT (Digital high/low sound peak trigger).",
    parameters: [
      { label: "Pickup Element", value: "Electret Condenser mic" },
      { label: "Frequency Scope", value: "50 Hz to 20,000 Hz" },
      { label: "Trigger Feed", value: "Onboard visual LED indicator" },
    ],
    trivia: "This sound sensor does not analyze complex speech or capture voice frequencies; it only detects whether sound volumes have exceeded a desired physical threshold.",
    hotspots: [
      { id: "snd_mic", name: "Electret Condenser Microphone", description: "Vibration-sensitive diaphragm that translates sound pressures into micro-volt electrical signals.", x: 20, y: 55 },
      { id: "snd_pot", name: "Sensitivity Threshold Trimmer", description: "Rotary screw resistor that changes the amplification threshold for triggering.", x: 50, y: 55 },
      { id: "snd_ic", name: "LM393 analog comparator chip", description: "Silicon chip comparing micro-volt signals with the threshold to determine high/low states.", x: 80, y: 55 }
    ],
  },
  {
    id: "sensor_microphone",
    name: "MAX4466 Analog Precision Mic",
    category: "sensor",
    symbol: "S-MIC",
    shortDesc: "High-gain analog microphone for audio recording.",
    description: "A high-fidelity electret microphone breakout board with an adjustable op-amp, perfect for voice recording and visual spectrum frequency analyzers.",
    howItWorks: "Processes analog audio pressures through a MAX4466 operational amplifier. It filters background electrical carrier noise and supplies a continuous analog voice waveform biased around half of the electrical input voltage.",
    realWorldExample: "Real-time spectrum sound equalizers, vocal frequency analyses, and voice recorders.",
    connections: "VCC (2.4V-5.5V super clean), GND, OUT (Analog direct audio sound wave).",
    parameters: [
      { label: "Amplifier IC", value: "MAX4466 Precision Op-Amp" },
      { label: "Sensing Gain", value: "Adjustable 25x to 125x" },
      { label: "Power Noise LDR", value: "Ultra-low power ripple rejection" },
    ],
    trivia: "To avoid recording digital clock jitter, power the MAX4466 from a dedicated analog linear low-drop regulator (LDO) rather than standard digital GPIO power rails.",
    hotspots: [
      { id: "mic_capsule", name: "Audio Electret Capsule", description: "A highly sensitive capacitive audio diaphragm capturing wide sound frequency spectrums.", x: 20, y: 50 },
      { id: "mic_amp", name: "MAX4466 Precision Op-Amp chip", description: "An ultra-low noise preamplifier that boosts audio wave amplitudes linearly.", x: 75, y: 50 }
    ],
  },
  {
    id: "sensor_tilt",
    name: "SW-520D Sphere Tilt Sensor",
    category: "sensor",
    symbol: "S-TLT",
    shortDesc: "Gravity roll-over and tip-over switch.",
    description: "A simple gravity-based orientation switch used to detect tilt, rollover coordinates, or physical structural tip-overs.",
    howItWorks: "Contains a small copper capsule with two gold-plated steel spheres. When tilted past 15°, gravity rolls the spheres onto matching metal pins, bridging the electrical circuit and alerting the MCU.",
    realWorldExample: "Chassis rollover failsafes, hazardous heater safety tips, and balance orientation alerts.",
    connections: "VCC, GND, OUT (Digital orientation level changed).",
    parameters: [
      { label: "Internal Elements", value: "Dual gold-plated contact balls" },
      { label: "Angle Threshold", value: "15° to 45° mechanical shift" },
      { label: "Current Load", value: "Under 5mA logic load only" },
    ],
    trivia: "Older tilt switches housed poisonous liquid mercury drops which switch without bouncing. SW-520D mechanical switches use gold spheres instead to safeguard user health.",
    hotspots: [
      { id: "tlt_cyl", name: "Conductive Metallic Tube", description: "A small brass shell housing two carbon-steel conductive sphere balls.", x: 50, y: 35 },
      { id: "tlt_balls", name: "Dual Carbon-Steel Spheres", description: "Rolling metallic spheres that bridge the internal contacts when tilted beyond 15 degrees.", x: 50, y: 65 },
      { id: "tlt_pins", name: "Sealed Golden Terminal Leads", description: "The direct electrical connection leads bridged by the spheres under gravity tilt.", x: 50, y: 85 }
    ],
  },
  {
    id: "sensor_vibration",
    name: "SW-420 Chassis Vibration Sensor",
    category: "sensor",
    symbol: "S-VIB",
    shortDesc: "High-sensitivity spring-based shake sensor.",
    description: "An active spring-driven vibration sensor designed to register rattles, physical strikes, drops, or motor shakes.",
    howItWorks: "A micro-fine brass spring floats inside a metal casing, surrounding a central wire terminal. Shock or vibrations cause the spring to flex and touch the central wire, completing the digital loop.",
    realWorldExample: "Robot landing impact recorders, car alarms, and industrial vibration guards.",
    connections: "VCC, GND, DO (Digital vibration shake flag).",
    parameters: [
      { label: "Spring Tension", value: "Normally-closed low-tension spring" },
      { label: "Active IC", value: "LM393 analog comparator" },
      { label: "Sensitivity Adjust", value: "Multi-Turn Trim Potentiometer" },
    ],
    trivia: "Because spring contacts rebound rapidly when shaken, you should implement software debounce code (ignoring double signals under 50ms) to ensure clean sensor readings.",
    hotspots: [
      { id: "vib_spring", name: "Conductive Internal Spring", description: "A micro-tension brass spring that curls around a central metal probe.", x: 40, y: 50 },
      { id: "vib_probe", name: "Central Metal Probe Wire", description: "Conductive center pin that registers a trigger when the spring oscillates and touches it.", x: 70, y: 50 }
    ],
  },
  {
    id: "sensor_rfid_rc522",
    name: "RC522 RFID Proximity Reader",
    category: "sensor",
    symbol: "S-FID",
    shortDesc: "Contactless 13.56MHz identity sensor.",
    description: "A contactless card scanner designed to read smart access badges, key fobs, and identification tags in real-time.",
    howItWorks: "Operates at 13.56 MHz. The card pad antenna shoots a high-frequency magnetic field. Approaching cards absorb this field via electromagnetic induction, power up an internal chip, and transmit their serial ID back to the RC522 board.",
    realWorldExample: "Smart door access locks, self-sorting warehouse bins, and interactive toy stations.",
    connections: "Uses SPI: SDA, SCK, MOSI, MISO, RST, 3.3V (NOT 5V!), GND.",
    parameters: [
      { label: "Operating Hertz", value: "13.56 MHz High-Frequency RFID" },
      { label: "Scan Distance", value: "2cm to 5cm distance" },
      { label: "Tag Protocols", value: "Mifare1 S50, S70, Ultralight" },
    ],
    trivia: "RFID tags have no battery of their own! They operate entirely off of electric power harvested inductively from the reader card's electromagnetic transmitter loop.",
    hotspots: [
      { id: "rfid_antenna", name: "PCB Serpentine Trace Antenna", description: "An array of loop traces generating a 13.56MHz electromagnetic field to power smart cards.", x: 50, y: 30 },
      { id: "rfid_ic", name: "MFRC522 High-Frequency IC", description: "The central silicon logic chip carrying high-speed RF processing and SPI protocol buffers.", x: 50, y: 70 }
    ],
  },
  {
    id: "sensor_fingerprint",
    name: "AS608 Optical Fingerprint Reader",
    category: "sensor",
    symbol: "S-FGP",
    shortDesc: "Biometric optical identity finger scanner.",
    description: "An optical biometric scanner designed to register, memorize, and match physical fingerprint patterns for system authorization.",
    howItWorks: "A blue-lit optical scanner takes high-contrast photographs of finger ridges. A built-in high-speed DSP chip extracts unique coordinates and matches them against templates stored in internal flash memory.",
    realWorldExample: "Keyless door locks, biometric starting triggers, and secure machinery panels.",
    connections: "VCC (3.3V-5V), GND, RX (Serial input), TX (Serial output). Standard baudrate 57600.",
    parameters: [
      { label: "Scan Resolution", value: "500 DPI high resolution" },
      { label: "Memory Space", value: "162 user fingerprint slots" },
      { label: "Match Time", value: "Less than 0.3 seconds average" },
    ],
    trivia: "The scanner stores fingerprints as encrypted mathematical hashes (vectors of ridge intersections), meaning it is impossible to reconstruct your actual fingerprint image from the chip's storage!",
    hotspots: [
      { id: "fgp_glass", name: "Optical Prism Glass Slot", description: "High-level glass prism directing blue laser waves onto the finger ridge print ridges.", x: 50, y: 30 },
      { id: "fgp_camera", name: "CMOS Image Capture Chip", description: "High-density micro camera recording the ridge shadow lines reflected off the prism.", x: 50, y: 55 },
      { id: "fgp_dsp", name: "High-Speed DSP Unit", description: "Digital Signal Processor executing hashing algorithms and saving user fingerprints in flash layout memory.", x: 50, y: 80 }
    ],
  },
  {
    id: "sensor_push_button",
    name: "Tactile Input Push Button",
    category: "sensor",
    symbol: "S-BTN",
    shortDesc: "Simple momentary tactile input switch.",
    description: "The fundamental input switch used for starting operations, resetting systems, navigating menus, or calibration prompts.",
    howItWorks: "Press-down tactile switch completing a physical copper bridge. Connecting the terminal loops channels VCC (HIGH) or GND (LOW) directly into a GPIO pin.",
    realWorldExample: "Industrial emergency stops, game controllers, and smart panel controls.",
    connections: "VCC, GND, OUT (Digital high/low push level).",
    parameters: [
      { label: "Switch Action", value: "Momentary tactile SPST" },
      { label: "Plunger Force", value: "160 ± 50 grams pressure" },
      { label: "Bounce Duration", value: "< 5 milliseconds bounce scale" },
    ],
    trivia: "TACT mechanical contacts bounce inside up to 30 times over several milliseconds. Microcontrollers use physical capacitors or quick software debounce checks to prevent multiple trigger events.",
    hotspots: [
      { id: "btn_cap", name: "Serrated Tactile Finger Plunger", description: "Molded round plastic button top transfering fingertip downward mechanical force.", x: 50, y: 35 },
      { id: "btn_dome", name: "Metallic Spring Contact Dome", description: "A tactile steel click plate that snaps down when pressed, bridging the PCB metal pads.", x: 50, y: 65 }
    ],
  },
  {
    id: "sensor_keypad",
    name: "4x4 Matrix Membrane Keypad",
    category: "sensor",
    symbol: "S-KEY",
    shortDesc: "16-Button membrane input code grid.",
    description: "A space-saving 16-key keypad array, ideal for security system passcodes, custom parameter entry, or motor selections.",
    howItWorks: "Connects 16 tactile pads onto a grid of 4 rows and 4 columns. A scanning program sequentially drives rows low and listens to column state drops to pinpoint coordinates without requiring 16 separate pins.",
    realWorldExample: "ATM vaults, secure terminal entries, and warehouse automated selectors.",
    connections: "8-pin female ribbon connector (4 row pins + 4 column pins).",
    parameters: [
      { label: "Grid Space", value: "16 buttons (0-9, A-D, *, #)" },
      { label: "GPIO Wire Lines", value: "8 logical pins needed" },
      { label: "Foil Profile", value: "1.2mm flat flexible strip" },
    ],
    trivia: "Using an 8-wire scanning matrix saves exactly 8 microcontroller pins, allowing you to connect other sensors that would otherwise be blocked by individual button grounds.",
    hotspots: [
      { id: "key_pads", name: "Tactile Dome Matrix Buttons", description: "Flexible tactile domes matching physical grid nodes (0-9, A-D) directly under the top foil matrix.", x: 50, y: 45 },
      { id: "key_ribbon", name: "Foil Ribbon Connection Cable", description: "Flat flexible ribbon layout carrying multiplexed rows and columns straight to host GPIO pins.", x: 50, y: 85 }
    ],
  },
  {
    id: "sensor_joystick",
    name: "Dual-Axis Analog Joystick",
    category: "sensor",
    symbol: "S-JOY",
    shortDesc: "Dual-axis thumbstick with microswitch.",
    description: "An analog joystick module optimized for steering robot wheels, navigating camera gimbal systems, or adjusting mechanical arm coordinates.",
    howItWorks: "Fitted with two independent 10k mechanical potentiometers that translate thumb-stick coordinates to analog voltages between 0V and 5V. Includes a center push-down microswitch joint.",
    realWorldExample: "Industrial crane controllers, robot arm controllers, and drone controls.",
    connections: "VCC, GND, VRx (Analog X axis), VRy (Analog Y axis), SW (Digital click button logic).",
    parameters: [
      { label: "Variable Resistors", value: "10,000 Ohm dual tracks" },
      { label: "Return Action", value: "Spring loaded snap-to-center" },
      { label: "Middle Volt Bias", value: "2.5V static output" },
    ],
    trivia: "The joystick's default center position reads approximately 2.5V (or 512 out of 1023 in Arduino 10-bit code). Programs often define a small center 'deadzone' to prevent drift.",
    hotspots: [
      { id: "joy_stick", name: "Spherical Thumbstick Cap Plunger", description: "Hard textured rubberized plunger on an omnidirectional hinge with return-to-center springs.", x: 50, y: 55 },
      { id: "joy_pot_x", name: "X-Axis Side Rotary Potentiometer", description: "A 10kOhm rotary potentiometer translating left-to-right stick travel into variable voltage ratios.", x: 20, y: 55 },
      { id: "joy_pot_y", name: "Y-Axis Top Rotary Potentiometer", description: "A 10kOhm potentiometer that transforms forward-to-backward tilt into a clean analog potential.", x: 50, y: 25 },
      { id: "joy_switch", name: "Tactile Press Click Z-Switch", description: "A momentary button below the card joint activated whenever the joystick is pushed directly down.", x: 80, y: 55 }
    ],
  },
  {
    id: "sensor_touch",
    name: "TTP223 Capacitive Touch Module",
    category: "sensor",
    symbol: "S-TCH",
    shortDesc: "Solid-state contact-free touch button.",
    description: "A responsive proximity sensor pad that registers touch through plastic sheets, glass panels, or thin wood covers.",
    howItWorks: "Tracks electromagnetic capacitance changes on its copper layout pad. Bringing a finger near changes the electric charge. A TTP223 chip processes this shift and switches the output pin to HIGH.",
    realWorldExample: "Sealed cleanroom lights, interactive museum displays, and waterproof panels.",
    connections: "VCC (2.5V - 5.5V support), GND, SIG (Binary direct trigger logic).",
    parameters: [
      { label: "Switch Chip", value: "TTP223 Capacitive IC" },
      { label: "Response Rate", value: "60 milliseconds latency" },
      { label: "Barrier Penetrance", value: "Up to 5mm thickness" },
    ],
    trivia: "Capacitive switches have no mechanical contacts inside that can wear down, offering infinite lifetime cycles and making them ideal for high-use public kiosks.",
    hotspots: [
      { id: "tch_pad", name: "Sensing Copper Target Pad", description: "Printed circular copper field detecting body charge deviations when fingers hover close.", x: 50, y: 40 },
      { id: "tch_ic", name: "TTP223 Charge Detector IC", description: "A tiny solid-state capacitive touch controller tracking precise change metrics.", x: 50, y: 75 }
    ],
  },
  {
    id: "actuator_relay",
    name: "5V Optoisolated Relay Module",
    category: "actuator",
    symbol: "A-RLY",
    shortDesc: "High-voltage magnetic switch relay.",
    description: "An electromagnetic isolated switch that lets low-power microcontrollers control high-voltage household appliances safely.",
    howItWorks: "A micro-volt logic signal fires an internal copper electromagnet coil. The coil pulls a spring hinge to bridge high-power circuits (like AC wall outlets) with a classic click.",
    realWorldExample: "Smart home lamps, sprinkler irrigation pumps, and automated door locks.",
    connections: "Control side: VCC (5V), GND, IN (Trigger). AC Side: COM (Common), NO (Normally Open), NC (Normally Closed) screw terminals.",
    parameters: [
      { label: "AC Current Limit", value: "10A @ 250V AC ratings" },
      { label: "DC Current Limit", value: "10A @ 30V DC ratings" },
      { label: "Isolated Barrier", value: "Onboard EL817 optocoupler" },
    ],
    trivia: "These modules use tiny optocouplers—which communicate purely via internal light pulses—to isolate AC lines and protect you and your microcontroller from catastrophic shocks.",
    hotspots: [
      { id: "rly_coil", name: "Electromag Copper Coil", description: "Wrapping wire which spawns a powerful electromagnetic field when 5V current runs.", x: 40, y: 45 },
      { id: "rly_spring", name: "Armature Return Spring", description: "Attracts the physical metallic switch flap and snaps it back to NO/NC default boundaries.", x: 40, y: 75 },
      { id: "rly_opto", name: "EL817 Optoisolated Gate", description: "Communicates triggers purely via an inner light-beam barrier, protecting your main MCU board.", x: 75, y: 35 },
      { id: "rly_screws", name: "AC Line Terminal Block Pins", description: "High-voltage isolated heavy-duty screw wire terminal block (Common, NO, NC).", x: 75, y: 75 }
    ],
  },
  {
    id: "actuator_solenoid_lock",
    name: "12V Electromagnetic Solenoid Lock",
    category: "actuator",
    symbol: "A-SLN",
    shortDesc: "Sub-second physical plunger cabinet lock.",
    description: "An active linear electromagnetic slider locker designed to lock safe boxes, cabinet doors, and mechanical bins.",
    howItWorks: "A high-density copper winding wraps around a steel piston arm. Supplying 12V DC generates a strong magnetic field, retracting the piston into the tube and releasing the lockout latch.",
    realWorldExample: "Smart drop boxes, automated library key trays, and vault door locks.",
    connections: "Needs N-Channel MOSFET or Relay to switch high load current. 12V High voltage DC lines.",
    parameters: [
      { label: "Nominal Volts", value: "12V DC line" },
      { label: "Current Pulls", value: "0.6A - 0.8A peak pulse flow" },
      { label: "Slider Travel", value: "10mm linear plunger slot" },
    ],
    trivia: "The solenoid plunger is spring-loaded, meaning the metal latch snaps back out to lock automatically as soon as battery power is switched off.",
    hotspots: [
      { id: "sol_coil", name: "High-Density Copper solenoid Winding", description: "A highly complex spiral coil layout that spawns a concentrated magnetic flux when 12V current passes.", x: 40, y: 55 },
      { id: "sol_plunger", name: "Carbon Steel Retractable Plunger Bolt", description: "Sliding key latch that gets pulled magnetoelectrically inside the chassis to open the locking door.", x: 75, y: 55 },
      { id: "sol_spring", name: "Carbon Return Tension Spring", description: "Pushes the bolt back out to secure cabinet frames the microsecond power is disconnected.", x: 20, y: 55 }
    ],
  },
  {
    id: "actuator_led_rgb",
    name: "5050 SMD Full-Color RGB Module",
    category: "actuator",
    symbol: "A-RGB",
    shortDesc: "Tri-color full spectral color LED module.",
    description: "A multi-color LED module capable of generating millions of spectrum colors by mixing Red, Green, and Blue light.",
    howItWorks: "Features Red, Green, and Blue sub-diodes. Varying the duty cycle of three PWM control signals maps RGB intensity ratios, creating millions of secondary colors like purple or orange.",
    realWorldExample: "Robot mood lighting, multi-state status lights, and smart displays.",
    connections: "R (Red PWM Pin), G (Green PWM Pin), B (Blue PWM Pin), - (Common ground).",
    parameters: [
      { label: "LED Variant Type", value: "SMD 5050 Common Cathode" },
      { label: "Spectrum Space", value: "16.7 million variations possible" },
      { label: "Power Limits", value: "20mA per active color lead" },
    ],
    trivia: "Mixing pure Red, Green, and Blue light waves in a dark room creates white light, a process known as additive color synthesis!",
    hotspots: [
      { id: "led_chip", name: "SMD 5050 RGB LED Element", description: "Houses three microscopic physical light-emitting chips (Red, Green, Blue) on a single ceramic substrate.", x: 35, y: 55 },
      { id: "led_resistors", name: "Current Limiting SMD Resistors", description: "Protects individual Red, Green, Blue sub-dies from running over current thresholds and burning down.", x: 75, y: 55 }
    ],
  },
  {
    id: "display_lcd1602",
    name: "16x2 Character I2C LCD",
    category: "actuator",
    symbol: "A-LCD",
    shortDesc: "16x2 text-character menu display screen.",
    description: "An easy-to-use alpha-numeric display capable of showing two lines of 16 characters each. Wired via I2C to save valuable microcontroller pins.",
    howItWorks: "Utilizes a liquid crystal display (LCD) layout biased by an HD44780 driver. Pin voltages alter crystal orientations to filter and format crisp, back-lit characters.",
    realWorldExample: "Industrial machinery readouts, robotics control panels, and sensor data screens.",
    connections: "VCC (5V main power), GND, SDA (I2C Data), SCL (I2C Clock).",
    parameters: [
      { label: "Letter Layout", value: "16 Characters x 2 Rows" },
      { label: "Interface IC", value: "PCF8574 I2C adapter backpack" },
      { label: "Contrast Adjust", value: "Rear blue trimmer screw" },
    ],
    trivia: "Using the I2C backpack board drops the necessary wiring pins from 12 parallel digital lines down to only 2 I2C wires, saving valuable GPIO real estate!",
    hotspots: [
      { id: "lcd_glass", name: "HD44780 Liquid Crystal Glass Panel", description: "Polarized glass panel showing sixteen characters across two lines via dynamic liquid crystals.", x: 50, y: 40 },
      { id: "lcd_chip", name: "I2C Expansion PCF8574 Backpack", description: "An 8-bit chip simplifying character signals into standard 2-wire serial SDA/SCL streams.", x: 50, y: 80 }
    ],
  },
  {
    id: "display_oled_ssd1306",
    name: "0.96 inch SSD1306 I2C OLED",
    category: "actuator",
    symbol: "A-OLD",
    shortDesc: "128x64 high-contrast organic graphic screen.",
    description: "A graphic display module used to render custom drawings, status icons, live line charts, or sensor data lists.",
    howItWorks: "Contains 128x64 independent Organic LEDs. High-speed I2C signals write pixel states directly to local RAM on an SSD1306 driver chip, displaying crisp graphic layouts.",
    realWorldExample: "Wearable smart rings, handheld meters, and diagnostic telemetry consoles.",
    connections: "VCC (3.3V or 5V regulator), GND, SDA, SCL.",
    parameters: [
      { label: "Dot Screen Space", value: "128 x 64 pixels density" },
      { label: "Driver Control", value: "SSD1306 I2C controller" },
      { label: "Spectral Emission", value: "Self-luminous (needs no backlight)" },
    ],
    trivia: "OLED pixels emit their own light. Displaying deep blacks turns the pixels off completely, which produces rich dark contrast ratios and drastically lowers power consumption.",
    hotspots: [
      { id: "oled_glass", name: "128x64 Organic Matrix Glass Screen", description: "High contrast glass matrix containing 8,192 self-emitting microscopic pixels.", x: 50, y: 42 },
      { id: "oled_ic", name: "SSD1306 Graphic driver", description: "Silicon chip handling high speed pixel writes and RAM buffers via serial digital commands.", x: 50, y: 78 }
    ],
  },
  {
    id: "display_seven_segment",
    name: "MAX7219 4-Digit 7-Segment",
    category: "actuator",
    symbol: "A-7SG",
    shortDesc: "4-Digit high-visibility numeric clock display.",
    description: "A bright numerical display designed to show time clocks, timer counters, distances, or state indices.",
    howItWorks: "Groups dozens of red LED bars into 8-shape wedges (7 segments + decimal dot per digit). A MAX7219 chip handles rapid switching multiplex loops to form clear numbers.",
    realWorldExample: "Stopwatches, vehicle speedometers, and digital clock scales.",
    connections: "VCC (5V), GND, DIN (Serial Data), CS (Chip select), CLK (Serial clock).",
    parameters: [
      { label: "Digits Count", value: "4 numbers + decimal dots" },
      { label: "Multiplexing", value: "MAX7219 active driver IC" },
      { label: "Bus Protocol", value: "High speed SPI interface" },
    ],
    trivia: "These displays multiplex lines faster than 1000Hz, switching numbers on and off so quickly that the human eye perceives them as constantly illuminated—an effect called persistence of vision.",
    hotspots: [
      { id: "seg_digits", name: "Four Multiplexed 7-Segment Digits", description: "Bright LED segments grouped into 8-shape slots to draw numerical characters.", x: 50, y: 45 },
      { id: "seg_ic", name: "MAX7219 Multiplexing Driver IC", description: "Saves microcontroller CPU power by sequencing the digits internally at speeds over 1kHz.", x: 50, y: 80 }
    ],
  },
  {
    id: "display_led_matrix",
    name: "MAX7219 8x8 LED Dot Matrix",
    category: "actuator",
    symbol: "A-MTX",
    shortDesc: "8x8 grid pixel matrix module.",
    description: "An 8x8 red LED dot grid, ideal for rendering status expressions, scrolling typography signs, or small retro games.",
    howItWorks: "An 8x8 grid of 64 LEDs mapped onto intersecting row-and-column arrays. A MAX7219 multiplexer handles active current distribution to save wiring and enable daisy chaining.",
    realWorldExample: "Scrolling highway text signs, robotics face displays, and diagnostic warning trackers.",
    connections: "VCC (5V), GND, DIN, CS, CLK (Chaining header DOUT is present).",
    parameters: [
      { label: "Active Pixels", value: "64 Red LED nodes (8x8 panel)" },
      { label: "Daisy Chain", value: "Connect multiple boards inline" },
      { label: "Logic Protocol", value: "3-Wire SPI Serial communications" },
    ],
    trivia: "You can daisy-chain dozens of these boards together horizontally. The SPI data flows out of the DOUT on one board back into the DIN on the next!",
    hotspots: [
      { id: "mtx_bubble", name: "8x8 Red LED Node Grid Array", description: "A high-intensity matrix containing sixty-four red light-emitting points.", x: 50, y: 42 },
      { id: "mtx_ic", name: "MAX7219 SPI Grid Driver chip", description: "An SPI chip handling multiplex duty cycles, brightness levels, and cascade lines.", x: 50, y: 82 }
    ],
  },
  {
    id: "controller_driver_l293d",
    name: "L293D Quad half-H Motor Shield",
    category: "motordriver",
    symbol: "C-293",
    shortDesc: "Compact low-power dual-motor driver chip.",
    description: "A popular, lightweight motor driver IC designed to run up to four DC motors or two bipolar stepper motors concurrently.",
    howItWorks: "Features quad high-current half-H drivers. Under micro-volt control pins, it channels larger battery voltages straight to positive and negative coil windings.",
    realWorldExample: "Educational robotic bugs, light motorized camera mounts, and smart drawer locks.",
    connections: "logical input pins, direct motor screw terminals, digital grounds.",
    parameters: [
      { label: "Output Drivers", value: "4 DC motors or 2 complex steppers" },
      { label: "Supply Current", value: "600mA continuous per line" },
      { label: "Supply Volts", value: "4.5V to 36.0V DC range" },
    ],
    trivia: "The 'D' in L293D stands for integrated flyback diodes, which absorb massive high-voltage reverse surges when motors brake rapidly, protecting adjacent electronics from melting down.",
    hotspots: [
      { id: "l293_ic", name: "L293D Dual H-Bridge Silicon", description: "Dual channel motor drive IC feeding external motors up to 600mA per axis.", x: 50, y: 55 },
      { id: "l293_clamp", name: "Rotary Screw Terminal Block Pins", description: "Convenient terminals to wire DC motors directly to the shield plate safely.", x: 78, y: 55 }
    ],
  },
  {
    id: "controller_driver_a4988",
    name: "A4988 DMOS Stepper Driver",
    category: "motordriver",
    symbol: "C-498",
    shortDesc: "Translator stepper driver module for 3D printers.",
    description: "A specialized micro-stepping motor driver board designed to coordinate precise, heavy bipolar steppers like NEMA 17.",
    howItWorks: "Translates standard STEP and DIR inputs into microstep currents. DIR sets the rotation direction (HIGH/LOW), and pulsing the STEP input steps the motor precisely.",
    realWorldExample: "Prusa 3D printer controller shields, CNC routers, and high accuracy medical scanners.",
    connections: "VMOT (Drive volts), VDD, STEP, DIR, Microstep selectors (MS1-MS3), phase pins A-B.",
    parameters: [
      { label: "Resolution Styles", value: "Full, 1/2, 1/4, 1/8, and 1/16 steps" },
      { label: "Safety Protections", value: "Overcurrent thermal shutdown circuits" },
      { label: "Drive Current Peak", value: "Up to 2.0 Amps max (with heatsink)" },
    ],
    trivia: "Microstepping matches currents on coil phases to hold rotor magnets at mid-step positions. Running a stepper in 1/16 step mode reduces motor noise drastically!",
    hotspots: [
      { id: "a4988_chip", name: "A4988 Stepper Translator", description: "Translates standard direction and microstep pulses into raw coil current waves.", x: 50, y: 58 },
      { id: "a4988_sink", name: "Aluminum Cooling Heatsink", description: "Small metal heatsink keeping DMOS switches under thermal safety limits.", x: 50, y: 28 }
    ],
  },
  {
    id: "comm_bluetooth_hc05",
    name: "HC-05 Serial UART Bluetooth",
    category: "sensor",
    symbol: "S-BTH",
    shortDesc: "Wireless serial Bluetooth data transceiver.",
    description: "A wireless transceiver module configured for Bluetooth SPP (Serial Port Profile) transmission, replacing physical serial wires with radio waves.",
    howItWorks: "Features a 2.4GHz radio chip and antenna. It manages wireless Bluetooth links and translates them into simple serial commands, letting phones communicate with robots.",
    realWorldExample: "Controlling rovers via mobile apps, wireless diagnostic feeds, and telemetry logs.",
    connections: "VCC (3.6V-6V power), GND, TX (Connect to Arduino RX), RX (Connect to Arduino TX via voltage slider).",
    parameters: [
      { label: "Radio Protocol", value: "Bluetooth v2.0 with EDR" },
      { label: "Reception Radius", value: "Up to 10 meters (30 feet)" },
      { label: "Baud Output", value: "9600 bps stock (supports up to 115k)" },
    ],
    trivia: "The HC-05 supports both Slave and Master mode, meaning that after programming with AT commands, two separate rovers can find and link to each other directly without a phone!",
    hotspots: [
      { id: "bt_antenna", name: "Meandered PCB Radio Antenna", description: "Sinuous trace configured to broadcast and receive 2.4GHz Bluetooth band signals.", x: 50, y: 20 },
      { id: "bt_chip", name: "BC417 Bluetooth Radio Single-Chip", description: "Houses the full Bluetooth baseband and SPP software layer to translate RF bytes to UART.", x: 50, y: 55 }
    ],
  },
  {
    id: "comm_wifi_esp8266",
    name: "ESP8266 ESP-01s WiFi Module",
    category: "sensor",
    symbol: "S-WIF",
    shortDesc: "Stand-alone micro WiFi network module.",
    description: "A tiny WiFi transceiver that connects basic Arduino microcontrollers to local routers, and local servers.",
    howItWorks: "Houses a self-contained 32-bit CPU running a full TCP/IP network stack. It receives AT commands over serial RX/TX, letting robots retrieve URLs or connect to household servers.",
    realWorldExample: "Uploading sensor logs to IoT clouds, hosting web server controllers on rovers, and building smart locks.",
    connections: "VCC (Strictly 3.3V!), GND, RX, TX, CH_PD (Chip select, pull HIGH), RST.",
    parameters: [
      { label: "IEEE Wireless Standard", value: "802.11 b/g/n (2.4 GHz band)" },
      { label: "Core Processing", value: "Tensilica 32-bit MCU processor" },
      { label: "Logic Constraints", value: "3.3V logic (NOT 5V tolerant!)" },
    ],
    trivia: "The ESP8266 series originally served as a basic Wi-Fi extension for Arduino until engineers realized they could program its internal processor directly, spawning a massive cheap IoT revolution.",
    hotspots: [
      { id: "wf_antenna", name: "Onboard Printed Copper Antenna", description: "Precisely tuned PCB antenna communicating with local 2.4GHz Wi-Fi networks.", x: 50, y: 22 },
      { id: "wf_mcu", name: "Tensilica 32-bit CPU SoC", description: "A 32-bit MCU chip packing a full TCP/IP system, handling connection links.", x: 50, y: 58 }
    ],
  },
  {
    id: "comm_rf_nrf24l01",
    name: "nRF24L01+ 2.4GHz RF Module",
    category: "sensor",
    symbol: "S-NRF",
    shortDesc: "High-speed low-latency RF communicator.",
    description: "A high-performance radio transceiver that enables low-latency radio communication, suitable for custom handheld remote controllers.",
    howItWorks: "Transmits packets directly across the 2.4GHz band without network connection delays. It operates at speeds up to 2 Mbps using hardware SPI, packing automatic packet retry logic.",
    realWorldExample: "Drones, game controllers, and multi-node robot team coordination.",
    connections: "VCC (Strictly 1.9V-3.6V!), GND, CE, CSN, SCK, MOSI, MISO (SPI interface pins).",
    parameters: [
      { label: "Hertz Channels", value: "125 independent frequency channels" },
      { label: "Transmission Rate", value: "250 kbps, 1 Mbps, or 2 Mbps speeds" },
      { label: "Line Of Sight Range", value: "Up to 100 meters distance" },
    ],
    trivia: "The nRF24L01 has a feature called 'MultiCeiver' that lets a single receiver coordinate and listen to up to six different remote robots simultaneously!",
    hotspots: [
      { id: "rf_antenna", name: "PCB Meander Line Antenna", description: "Printed meander trace to stream high speed packet payloads under 2.4GHz channels.", x: 50, y: 22 },
      { id: "rf_ic", name: "nRF24L01+ High-Performance RF IC", description: "The core transceiver tracking packet loops, shockburst frames, and automatic handshakes.", x: 50, y: 58 }
    ],
  },
];

// Dynamically assign sensor applications to relevant parts
const SENSOR_APP_MAP: Record<string, "sound" | "touch" | "vision" | "light" | "environment" | "motion" | "security"> = {
  sensor_ultrasonic: "sound",
  sensor_imu_mpu6050: "motion",
  sensor_camera: "vision",
  sensor_ir_tracker: "light",
  sensor_ir_obstacle: "light",
  sensor_pir_motion: "motion",
  sensor_dht11: "environment",
  sensor_soil_moisture: "environment",
  sensor_rain: "environment",
  sensor_gas_mq2: "environment",
  sensor_ldr: "light",
  sensor_sound: "sound",
  sensor_microphone: "sound",
  sensor_tilt: "motion",
  sensor_vibration: "motion",
  sensor_rfid_rc522: "security",
  sensor_fingerprint: "security",
  sensor_push_button: "touch",
  sensor_keypad: "touch",
  sensor_joystick: "touch",
  sensor_touch: "touch",
};

ROBOTIC_PARTS.forEach(part => {
  if (part.category === "sensor" && SENSOR_APP_MAP[part.id]) {
    part.sensorApplication = SENSOR_APP_MAP[part.id];
  }
});

export const ROBOTICS_QUIZ: QuizQuestion[] = [
  {
    id: "q1",
    question: "Why should you NOT power a high-drawn DC Motor directly from an Arduino Uno output pin?",
    options: [
      "The microcontroller pins can only source about 40mA, and drawing heavy motor current can burn out the chip's internal gates.",
      "DC motors run on alternating current (AC), while microcontrollers can only supply highly stable direct current (DC).",
      "Arduino code only executes clockwise motor instructions; counter-clockwise directions require specialized firmware.",
      "The output pins of microcontrollers are configured as analog inputs and cannot provide any output power.",
    ],
    correctAnswerIndex: 0,
    explanation: "Microcontroller pins are designed for logic signals, not power delivery. Most can supply up to 20-40 milliamps max. A stalled DC motor can draw over 1000 milliamps (1A), which will immediately destroy the microcontroller's internal transistor gates. This is why we use Motor Drivers as intermediate power bridges!",
    category: "microcontroller",
  },
  {
    id: "q2",
    question: "If a student wants a mechanical arm claw to move to exactly 90 degrees and safely hold its physical position, which actuator is best?",
    options: [
      "A geared continuously spinning Hobby DC Motor",
      "A precision Closed-Loop Servo Motor",
      "An unmanaged inductive Solenoid slide",
      "A high-speed industrial Pneumatic compressor",
    ],
    correctAnswerIndex: 1,
    explanation: "Servo Motors operate under a 'Closed-Loop' system. They take in an exact target angle signal and use internal feedback (from a potentiometer) to drive their motor until they match that exact angle, working continuously to oppose any external forces trying to rotate them away.",
    category: "actuator",
  },
  {
    id: "q3",
    question: "An Ultrasonic distance sensor determines distance by timing how long soundwaves take to bounce back. If a target is closer, what happens to the Return Pulse width on the Echo pin?",
    options: [
      "The return pulse becomes wider (takes more microseconds to generate).",
      "The return pulse becomes shorter (takes fewer microseconds to generate).",
      "The pulse frequency changes from 40kHz to 100Hz.",
      "The return pulse voltage drops from 5V to 0V indefinitely.",
    ],
    correctAnswerIndex: 1,
    explanation: "The ECHO output pin stays high (5V) for the exact duration it takes the sound wave to travel to the target and bounce back. Because sound travels at a fixed speed, a closer object means a shorter travel time, which produces a shorter high-pulse duration on the Echo pin.",
    category: "sensor",
  },
  {
    id: "q4",
    question: "What is the primary difference with MEMS technology used inside miniature devices like gyroscopes and accelerometers?",
    options: [
      "They are made out of biological cells and run on metabolic glucose.",
      "They are microscopic mechanical sensors and electronic logic elements etched directly into a single silicon wafer.",
      "They only operate when exposed to direct space cosmic rays for power.",
      "They don't have electronic outputs and only convey physical fluids.",
    ],
    correctAnswerIndex: 1,
    explanation: "MEMS stands for Micro-Electro-Mechanical Systems. They contain miniature mechanical parts (springs, plates, beams) sized in micrometers, etched into silicon alongside electronic processing circuits, allowing complex movement tracking in tiny everyday microchips.",
    category: "sensor",
  },
  {
    id: "q5",
    question: "Why do we use an H-Bridge driver circuit (like the L298N) for wheel-drive motors?",
    options: [
      "To step down DC battery power from 12V to continuous 3.3V safely.",
      "To allow the motor direction to be reversed by swapping the power polarity using coordinated high-power switch gates.",
      "To convert wireless Wi-Fi signals directly into mechanical wheel rotations.",
      "To count wheel rotations and act as high precision rotary encoders.",
    ],
    correctAnswerIndex: 2,
    explanation: "An H-bridge uses 4 electronic power switches arranged like an 'H'. Turning on opposite diagonal pairs of switches controls which way current flows through the motor. Swapping which pair of switches is active reverses the polarity, allowing the motor to spin backward or forward.",
    category: "motordriver",
  },
];
